# Generated by Django 4.2.13 on 2024-07-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('S', 'Science&Tech'), ('F', 'Fiction'), ('B', 'Biography'), ('T', 'Travel'), ('O', 'Other')], default='S', max_length=1),
        ),
    ]
